name: Deploy to Production

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=prod-

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Deploy to production environment (Blue-Green)
        run: |
          echo "Deploying to production environment with blue-green strategy..."
          # Add your production deployment commands here
          # Example: kubectl apply -f k8s/production/
          # Example: Implement blue-green deployment strategy
        continue-on-error: true

      - name: Run health checks
        run: |
          echo "Running production health checks..."
          sleep 60
          # curl -f https://api.healthflow.egypt.gov/health || echo "Health check completed"
          # curl -f https://healthflow.egypt.gov || echo "Frontend health check completed"
        continue-on-error: true

      - name: Run post-deployment tests
        run: |
          echo "Running post-deployment tests..."
          # Add post-deployment test commands here
        continue-on-error: true

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, initiating rollback..."
          # Add rollback commands here
        continue-on-error: true

      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        if: always() && env.SLACK_WEBHOOK_URL != ''
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          text: 'Production deployment completed'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

